-- ============================================================
-- OpenVAL Schema - Part 6: Gap Closure + Multi-Database Notes
-- Version: 1.0.0
-- Run after Parts 1-5
--
-- This part closes all gaps identified in the full requirements
-- audit. Each table has a note on Oracle/MySQL equivalents.
-- The raw DDL here is PostgreSQL. Oracle and MySQL versions
-- are auto-generated by scripts/generate_schema.py
-- ============================================================

-- ============================================================
-- SECTION 1: USER ACCESS REVIEWS
-- 21 CFR 11.10(d) requires periodic review of who has access.
-- This is standard in every regulated environment - QA reviews
-- all system user accounts at least annually. FDA inspectors
-- specifically ask for evidence of access reviews.
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS seq_access_review_ref START 1;

CREATE TABLE user_access_reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    review_ref VARCHAR(50) UNIQUE NOT NULL,     -- UAR-0001
    site_id UUID NOT NULL REFERENCES sites(id),
    system_id UUID REFERENCES systems(id),      -- NULL = OpenVAL itself
    review_type VARCHAR(50) NOT NULL DEFAULT 'periodic',
    -- periodic | triggered | post_incident | pre_inspection
    review_period_start DATE NOT NULL,
    review_period_end DATE NOT NULL,
    conducted_by UUID NOT NULL REFERENCES users(id),
    qa_reviewer_id UUID REFERENCES users(id),
    status VARCHAR(50) NOT NULL DEFAULT 'open',
    -- open | in_progress | complete | approved
    total_accounts_reviewed INT NOT NULL DEFAULT 0,
    accounts_confirmed_appropriate INT NOT NULL DEFAULT 0,
    accounts_requiring_action INT NOT NULL DEFAULT 0,
    accounts_removed INT NOT NULL DEFAULT 0,
    accounts_modified INT NOT NULL DEFAULT 0,
    overall_finding TEXT,
    -- satisfactory | minor_issues | major_issues
    conclusion TEXT,
    approved_by UUID REFERENCES users(id),
    approved_at TIMESTAMPTZ,
    signature_id UUID REFERENCES electronic_signatures(id),
    next_review_date DATE,
    regulatory_citation VARCHAR(255) DEFAULT '21 CFR 11.10(d)',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

CREATE TABLE user_access_review_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    review_id UUID NOT NULL REFERENCES user_access_reviews(id),
    reviewed_user_id UUID NOT NULL REFERENCES users(id),
    reviewed_username VARCHAR(100) NOT NULL,     -- snapshot
    reviewed_user_name VARCHAR(255) NOT NULL,    -- snapshot
    roles_at_review TEXT NOT NULL,               -- JSON snapshot of roles
    last_login_at TIMESTAMPTZ,
    account_status VARCHAR(50) NOT NULL,         -- active | locked | never_logged_in
    finding VARCHAR(50) NOT NULL DEFAULT 'appropriate',
    -- appropriate | excessive_access | no_longer_required
    -- never_logged_in | duplicate | needs_role_change
    action_required VARCHAR(100),
    -- none | deactivate | reduce_access | change_role | contact_manager
    action_taken VARCHAR(100),
    action_taken_by UUID REFERENCES users(id),
    action_taken_at TIMESTAMPTZ,
    reviewer_comments TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id)
);

-- ============================================================
-- SECTION 2: REVALIDATION EVENT TRACKING
-- Tracks each revalidation event separately from the original
-- validation project. Sites often ask: "When was this last
-- revalidated? What triggered it? What was the outcome?"
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS seq_revalidation_ref START 1;

CREATE TABLE revalidation_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_ref VARCHAR(50) UNIQUE NOT NULL,       -- REVAL-0001
    system_id UUID NOT NULL REFERENCES systems(id),
    project_id UUID REFERENCES validation_projects(id),
    trigger_type VARCHAR(100) NOT NULL,
    -- major_version_upgrade | minor_version_upgrade | patch_release
    -- infrastructure_change | configuration_change | security_patch
    -- periodic_review_outcome | regulatory_requirement | incident
    -- vendor_notification | audit_finding | capa_driven
    trigger_description TEXT NOT NULL,
    trigger_date DATE NOT NULL,
    triggering_change_request_id UUID REFERENCES change_requests(id),
    triggering_capa_id UUID REFERENCES capas(id),
    triggering_audit_finding_id UUID REFERENCES audit_findings(id),
    -- Scope assessment
    scope_assessment TEXT NOT NULL,
    -- What was assessed: full revalidation vs targeted
    revalidation_scope VARCHAR(50) NOT NULL DEFAULT 'targeted',
    -- full | targeted | equivalence | documentation_only
    scope_justification TEXT NOT NULL,
    prior_validation_date DATE,
    -- Outcome
    status VARCHAR(50) NOT NULL DEFAULT 'open',
    -- open | in_progress | complete | cancelled
    conclusion VARCHAR(50),
    -- validated | conditionally_validated | not_validated
    conclusion_narrative TEXT,
    completed_date DATE,
    next_revalidation_trigger TEXT,              -- What would trigger next reval
    -- Approval
    approved_by UUID REFERENCES users(id),
    approved_at TIMESTAMPTZ,
    signature_id UUID REFERENCES electronic_signatures(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

-- ============================================================
-- SECTION 3: DISASTER RECOVERY / BCP TEST RECORDS
-- 21 CFR Part 11 and EU Annex 11 §16 require that backup
-- and recovery procedures are tested. Sites need a record of
-- DR tests including what was tested, results, and sign-off.
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS seq_dr_test_ref START 1;

CREATE TABLE dr_bcp_tests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_ref VARCHAR(50) UNIQUE NOT NULL,        -- DR-0001
    site_id UUID NOT NULL REFERENCES sites(id),
    system_id UUID REFERENCES systems(id),       -- NULL = full site DR
    test_type VARCHAR(100) NOT NULL,
    -- backup_restore | failover | full_dr | tabletop | partial_restore
    -- point_in_time_recovery | media_restoration
    test_date DATE NOT NULL,
    test_scope TEXT NOT NULL,
    -- What was tested: which systems, what data, which recovery scenario
    rto_target_hours DECIMAL(5,2),               -- Recovery Time Objective
    rpo_target_hours DECIMAL(5,2),               -- Recovery Point Objective
    rto_actual_hours DECIMAL(5,2),
    rpo_actual_hours DECIMAL(5,2),
    backup_date_used DATE,                        -- Which backup was restored
    test_environment VARCHAR(100),               -- isolated | staging | production
    led_by UUID REFERENCES users(id),
    participants TEXT,                           -- JSON array of user IDs
    -- Scenario tested
    failure_scenario TEXT NOT NULL,
    -- Steps executed
    steps_executed TEXT,                         -- JSON array of steps with results
    -- Results
    result VARCHAR(50) NOT NULL,
    -- pass | fail | partial | not_tested
    rto_met BOOLEAN,
    rpo_met BOOLEAN,
    data_integrity_verified BOOLEAN NOT NULL DEFAULT FALSE,
    audit_trail_intact BOOLEAN,
    findings TEXT,
    recommendations TEXT,
    follow_up_actions TEXT,                      -- JSON array of action items
    -- GxP specific
    gxp_systems_included BOOLEAN NOT NULL DEFAULT FALSE,
    gxp_data_verified BOOLEAN,
    electronic_records_accessible BOOLEAN,
    -- Approval
    reviewed_by UUID REFERENCES users(id),
    reviewed_at TIMESTAMPTZ,
    approved_by UUID REFERENCES users(id),
    approved_at TIMESTAMPTZ,
    signature_id UUID REFERENCES electronic_signatures(id),
    next_test_date DATE,
    regulatory_citation VARCHAR(255) DEFAULT 'EU Annex 11 §16',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

-- ============================================================
-- SECTION 4: ANALYTICAL/METHOD VALIDATION
-- MAV (Method Analytical Validation) is in the protocol types
-- but needs structured data tables for the specific parameters
-- required by ICH Q2(R1): specificity, linearity, range,
-- accuracy, precision, detection/quantitation limits, robustness.
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS seq_method_val_ref START 1;

CREATE TABLE method_validations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    method_ref VARCHAR(50) UNIQUE NOT NULL,      -- MAV-0001
    site_id UUID NOT NULL REFERENCES sites(id),
    protocol_id UUID REFERENCES protocols(id),
    method_name VARCHAR(512) NOT NULL,
    method_code VARCHAR(100),
    method_type VARCHAR(100) NOT NULL,
    -- assay | identification | limit_test | quantitative | dissolution
    -- microbiology | environmental | raw_material | stability
    product_matrix VARCHAR(255),                 -- What is being tested
    analyte VARCHAR(255),                        -- What is being measured
    instrument_id UUID REFERENCES equipment(id),
    regulatory_basis VARCHAR(255) DEFAULT 'ICH Q2(R1)',
    validation_type VARCHAR(100) NOT NULL DEFAULT 'full',
    -- full | partial | revalidation | transfer | verification
    status VARCHAR(50) NOT NULL DEFAULT 'draft',
    -- Parameters determined (filled in by execution results)
    specificity_result VARCHAR(50),              -- pass | fail | not_applicable
    linearity_r_squared DECIMAL(10,8),
    linearity_result VARCHAR(50),
    range_lower VARCHAR(100),
    range_upper VARCHAR(100),
    range_unit VARCHAR(50),
    range_result VARCHAR(50),
    accuracy_mean_recovery DECIMAL(10,4),
    accuracy_rsd DECIMAL(10,4),
    accuracy_result VARCHAR(50),
    repeatability_rsd DECIMAL(10,4),
    repeatability_result VARCHAR(50),
    intermediate_precision_rsd DECIMAL(10,4),
    intermediate_precision_result VARCHAR(50),
    reproducibility_rsd DECIMAL(10,4),
    lod_value DECIMAL(20,8),
    lod_unit VARCHAR(50),
    loq_value DECIMAL(20,8),
    loq_unit VARCHAR(50),
    robustness_result VARCHAR(50),
    system_suitability_criteria TEXT,
    -- Overall outcome
    overall_result VARCHAR(50),
    conclusion TEXT,
    approved_by UUID REFERENCES users(id),
    approved_at TIMESTAMPTZ,
    signature_id UUID REFERENCES electronic_signatures(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

-- Method validation parameter detail results
CREATE TABLE method_validation_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    method_id UUID NOT NULL REFERENCES method_validations(id),
    parameter_type VARCHAR(100) NOT NULL,
    -- specificity | linearity | range | accuracy | repeatability
    -- intermediate_precision | reproducibility | lod | loq | robustness
    -- system_suitability | filter_validation | solution_stability
    experiment_description TEXT NOT NULL,
    acceptance_criteria TEXT NOT NULL,
    result_data TEXT NOT NULL,                   -- JSON structured data
    computed_statistics TEXT,                    -- JSON: mean, rsd, r2, etc.
    result VARCHAR(50) NOT NULL,                 -- pass | fail | not_applicable
    analyst_id UUID REFERENCES users(id),
    experiment_date DATE,
    instrument_id UUID REFERENCES equipment(id),
    comments TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

-- ============================================================
-- SECTION 5: EXTERNAL SYSTEM ACCESS LOG
-- Tracks when users log into external GxP systems (LIMS, MES,
-- ERP) that OpenVAL integrates with. Required for demonstrating
-- that access controls and audit trails cover the full scope
-- of GxP data handling, not just OpenVAL itself.
-- ============================================================

CREATE TABLE external_system_access_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    system_id UUID NOT NULL REFERENCES systems(id),
    user_id UUID REFERENCES users(id),           -- NULL if user not in OpenVAL
    external_username VARCHAR(255) NOT NULL,
    access_type VARCHAR(50) NOT NULL,
    -- login | logout | session_timeout | failed_login | privilege_escalation
    ip_address VARCHAR(45),
    workstation_id VARCHAR(255),
    source VARCHAR(50) NOT NULL DEFAULT 'integration',
    -- integration | manual_entry | csv_import | audit_review
    occurred_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw_event_data TEXT,                         -- Original log entry JSON
    notes TEXT
);

-- ============================================================
-- SECTION 6: DATA MIGRATION / LEGACY IMPORT TRACKING
-- When systems are replaced or upgraded and data is migrated
-- from legacy systems, 21 CFR Part 11 requires validation of
-- the migration process. Records must demonstrate that migrated
-- data is complete, accurate, and attributable.
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS seq_migration_ref START 1;

CREATE TABLE data_migrations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    migration_ref VARCHAR(50) UNIQUE NOT NULL,   -- MIG-0001
    site_id UUID NOT NULL REFERENCES sites(id),
    source_system_name VARCHAR(512) NOT NULL,    -- Legacy system name
    source_system_id UUID REFERENCES systems(id),
    target_system_id UUID NOT NULL REFERENCES systems(id),
    migration_type VARCHAR(100) NOT NULL,
    -- full_migration | partial_migration | historical_archive
    -- data_transformation | format_conversion
    migration_scope TEXT NOT NULL,
    -- What data: date ranges, record types, volumes
    validation_approach TEXT NOT NULL,
    -- How migration was validated: spot check, 100% verification, statistical
    status VARCHAR(50) NOT NULL DEFAULT 'planned',
    -- planned | in_progress | complete | failed | cancelled
    planned_date DATE,
    actual_start_date DATE,
    actual_completion_date DATE,
    -- Volume metrics
    records_to_migrate BIGINT,
    records_migrated BIGINT,
    records_verified BIGINT,
    records_failed BIGINT,
    records_excluded BIGINT,
    -- Data integrity validation
    pre_migration_hash TEXT,                     -- Hash of source data
    post_migration_hash TEXT,                    -- Hash of migrated data
    hash_match BOOLEAN,
    sampling_method VARCHAR(100),
    sampling_percentage DECIMAL(5,2),
    -- Exceptions
    exceptions_count INT NOT NULL DEFAULT 0,
    exceptions_description TEXT,
    exceptions_resolved BOOLEAN,
    -- Approval
    performed_by UUID REFERENCES users(id),
    verified_by UUID REFERENCES users(id),
    approved_by UUID REFERENCES users(id),
    approved_at TIMESTAMPTZ,
    signature_id UUID REFERENCES electronic_signatures(id),
    change_request_id UUID REFERENCES change_requests(id),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

CREATE TABLE data_migration_exceptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    migration_id UUID NOT NULL REFERENCES data_migrations(id),
    record_identifier VARCHAR(512) NOT NULL,     -- Which record failed
    record_type VARCHAR(100),
    exception_type VARCHAR(100) NOT NULL,
    -- missing_data | format_mismatch | integrity_error | transformation_error
    exception_description TEXT NOT NULL,
    source_data TEXT,                            -- What was in source
    target_data TEXT,                            -- What ended up in target
    resolution VARCHAR(100),
    -- migrated_as_is | excluded | manually_corrected | data_unavailable
    resolution_notes TEXT,
    resolved_by UUID REFERENCES users(id),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- SECTION 7: 21 CFR PART 4 - COMBINATION PRODUCTS
-- Structured classification for combination products that
-- fall under both drug and device regulations.
-- Partial support existed; this adds proper structure.
-- ============================================================

CREATE TABLE combination_product_classifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    system_id UUID NOT NULL REFERENCES systems(id),
    product_name VARCHAR(512) NOT NULL,
    classification_type VARCHAR(100) NOT NULL,
    -- drug_device | drug_biologic | device_biologic | all_three
    primary_mode_of_action VARCHAR(50) NOT NULL,
    -- drug | device | biologic
    primary_center VARCHAR(100) NOT NULL,
    -- CDER | CDRH | CBER
    applicable_regulations TEXT NOT NULL,        -- JSON array: which CFRs apply
    intercenter_agreement BOOLEAN NOT NULL DEFAULT FALSE,
    rfo_number VARCHAR(100),                     -- Request for Designation number
    designation_date DATE,
    classification_rationale TEXT NOT NULL,
    validated BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id),
    UNIQUE (system_id)
);

-- ============================================================
-- SECTION 8: SUPPLIER CONTROLS
-- 21 CFR 820.50 (medical devices) and 21 CFR 211.84/211.122
-- (pharma) require supplier controls beyond qualification.
-- Includes approved supplier list, receiving inspection,
-- supplier performance monitoring.
-- ============================================================

CREATE TABLE approved_supplier_list (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vendor_id UUID NOT NULL REFERENCES vendors(id),
    site_id UUID NOT NULL REFERENCES sites(id),
    material_or_service VARCHAR(512) NOT NULL,
    -- What specifically is approved (not just the vendor)
    approval_category VARCHAR(100) NOT NULL,
    -- raw_material | packaging | api | reagent | service | equipment
    -- software | contract_lab | contract_manufacturer
    approval_basis VARCHAR(255),
    -- audit | questionnaire | certificate_review | history | approved_by_customer
    approval_date DATE NOT NULL,
    reapproval_date DATE,
    approval_status VARCHAR(50) NOT NULL DEFAULT 'approved',
    -- approved | conditionally_approved | disqualified | on_hold | pending
    conditions TEXT,
    approved_by UUID REFERENCES users(id),
    regulatory_requirement VARCHAR(255),
    -- 21 CFR 211.84 | 21 CFR 820.50 | ISO 13485 7.4
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

CREATE TABLE supplier_performance_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    vendor_id UUID NOT NULL REFERENCES vendors(id),
    site_id UUID NOT NULL REFERENCES sites(id),
    review_period_start DATE NOT NULL,
    review_period_end DATE NOT NULL,
    reviewed_by UUID REFERENCES users(id),
    review_date DATE NOT NULL,
    -- Performance metrics
    deliveries_on_time INT,
    deliveries_total INT,
    on_time_delivery_pct DECIMAL(5,2),
    complaints_raised INT NOT NULL DEFAULT 0,
    nonconformances_raised INT NOT NULL DEFAULT 0,
    capas_raised INT NOT NULL DEFAULT 0,
    audit_findings_count INT NOT NULL DEFAULT 0,
    -- Overall rating
    performance_rating VARCHAR(50),
    -- excellent | satisfactory | needs_improvement | unsatisfactory
    narrative TEXT,
    action_required BOOLEAN NOT NULL DEFAULT FALSE,
    action_description TEXT,
    -- Continued approval decision
    continued_approval VARCHAR(50) NOT NULL DEFAULT 'approved',
    -- approved | conditionally_approved | disqualified | under_review
    approved_by UUID REFERENCES users(id),
    signature_id UUID REFERENCES electronic_signatures(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

-- ============================================================
-- SECTION 9: PROCESS ENGINEERING STRUCTURED TABLES
-- Original requirement: "pharma AND process engineering"
-- Structured CPP/CQA linkage, process capability tracking,
-- and process performance qualification (PPQ) support
-- beyond the analytics tables already in Part 3.
-- ============================================================

CREATE TABLE process_capability_studies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    study_ref VARCHAR(50) UNIQUE NOT NULL,
    site_id UUID NOT NULL REFERENCES sites(id),
    system_id UUID REFERENCES systems(id),
    process_name VARCHAR(512) NOT NULL,
    study_type VARCHAR(100) NOT NULL DEFAULT 'ppq',
    -- ppq | continued_process_verification | stage3_validation
    -- capability_study | process_performance_review
    product_name VARCHAR(255),
    process_step VARCHAR(255),
    parameter_id UUID REFERENCES process_parameters(id),
    study_start_date DATE,
    study_end_date DATE,
    batches_evaluated INT,
    -- Capability statistics
    lsl DECIMAL(20,6),                           -- Lower Spec Limit
    usl DECIMAL(20,6),                           -- Upper Spec Limit
    target_value DECIMAL(20,6),
    unit VARCHAR(50),
    mean_value DECIMAL(20,6),
    std_deviation DECIMAL(20,6),
    cp DECIMAL(10,4),                            -- Process capability
    cpk DECIMAL(10,4),                           -- Process capability index
    pp DECIMAL(10,4),                            -- Process performance
    ppk DECIMAL(10,4),                           -- Process performance index
    -- ICH Q10 Stage 3 continued process verification
    cpv_status VARCHAR(50),
    -- in_control | out_of_control | trending | requires_investigation
    within_spec_pct DECIMAL(5,2),
    -- Outcome
    capability_conclusion VARCHAR(100),
    -- capable | marginally_capable | not_capable
    conclusion_narrative TEXT,
    approved_by UUID REFERENCES users(id),
    approved_at TIMESTAMPTZ,
    signature_id UUID REFERENCES electronic_signatures(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

-- CPP/CQA linkage (formal linkage between critical parameters and quality attributes)
CREATE TABLE cpp_cqa_linkages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    site_id UUID NOT NULL REFERENCES sites(id),
    system_id UUID REFERENCES systems(id),
    cpp_parameter_id UUID REFERENCES process_parameters(id),
    cpp_name VARCHAR(512) NOT NULL,
    cqa_name VARCHAR(512) NOT NULL,
    linkage_type VARCHAR(50) NOT NULL DEFAULT 'impact',
    -- impact | control | monitoring
    impact_level VARCHAR(50) NOT NULL,
    -- critical | major | minor | none
    impact_rationale TEXT NOT NULL,
    control_strategy TEXT,
    pac_lower VARCHAR(100),                      -- Proven Acceptable Range lower
    pac_upper VARCHAR(100),                      -- Proven Acceptable Range upper
    risk_assessment_id UUID REFERENCES risk_assessments(id),
    risk_item_id UUID REFERENCES risk_items(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

-- ============================================================
-- SECTION 10: ID_SEQUENCES TABLE FOR MYSQL COMPATIBILITY
-- PostgreSQL and Oracle use native sequences.
-- MySQL requires this simulation table.
-- The application uses this table when dialect = mysql.
-- ============================================================

CREATE TABLE id_sequences (
    seq_name VARCHAR(100) PRIMARY KEY,
    current_value BIGINT NOT NULL DEFAULT 0,
    increment_by INT NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Populate with all sequence names used in the application
INSERT INTO id_sequences (seq_name, current_value) VALUES
('system_ref', 0), ('equipment_ref', 0), ('risk_assessment_ref', 0),
('requirement_set_ref', 0), ('protocol_ref', 0), ('test_execution_ref', 0),
('deviation_ref', 0), ('document_ref', 0), ('change_request_ref', 0),
('capa_ref', 0), ('nc_ref', 0), ('periodic_review_ref', 0),
('traceability_matrix_ref', 0), ('vendor_ref', 0), ('vendor_qualification_ref', 0),
('vendor_audit_ref', 0), ('audit_ref', 0), ('audit_finding_ref', 0),
('training_ref', 0), ('report_ref', 0), ('workflow_ref', 0),
('workflow_instance_ref', 0), ('form_ref', 0), ('form_submission_ref', 0),
('signature_id', 0), ('audit_event_id', 0), ('file_ref', 0),
('change_task_ref', 0), ('calibration_ref', 0), ('maintenance_ref', 0),
('oos_ref', 0), ('complaint_ref', 0), ('em_session_ref', 0),
('em_excursion_ref', 0), ('stability_ref', 0), ('batch_ref', 0),
('coa_ref', 0), ('inspection_ref', 0), ('val_project_ref', 0),
('val_plan_ref', 0), ('val_report_ref', 0), ('protocol_amendment_ref', 0),
('open_item_ref', 0), ('config_baseline_ref', 0), ('access_review_ref', 0),
('revalidation_ref', 0), ('dr_test_ref', 0), ('method_val_ref', 0),
('migration_ref', 0)
ON CONFLICT (seq_name) DO NOTHING;

-- ============================================================
-- SECTION 11: DATABASE COMPATIBILITY NOTES TABLE
-- Documents which GxP controls are active for the current
-- database deployment. Inspectors may ask what controls are
-- in place. This table provides the answer at runtime.
-- ============================================================

CREATE TABLE database_compliance_controls (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    db_dialect VARCHAR(50) NOT NULL,
    -- postgresql | oracle | mysql | mariadb
    control_name VARCHAR(255) NOT NULL,
    control_type VARCHAR(100) NOT NULL,
    -- database_layer | application_layer | hybrid
    description TEXT NOT NULL,
    regulatory_citation VARCHAR(512),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    implementation_notes TEXT,
    UNIQUE (db_dialect, control_name)
);

INSERT INTO database_compliance_controls
    (db_dialect, control_name, control_type, description, regulatory_citation, is_active) VALUES
('postgresql', 'Audit Log Append-Only (RLS)',    'database_layer',
 'PostgreSQL Row Level Security prevents UPDATE/DELETE on audit_log table at database layer. No application code can bypass this.',
 '21 CFR 11.10(e)', true),
('postgresql', 'Signature Append-Only (RLS)',    'database_layer',
 'PostgreSQL Row Level Security prevents UPDATE/DELETE on electronic_signatures table.',
 '21 CFR 11.70', true),
('postgresql', 'Full-Text Search (pg_trgm)',     'database_layer',
 'Trigram indexes enable high-performance full-text search.',
 NULL, true),
('oracle', 'Audit Log Append-Only (VPD)',        'database_layer',
 'Oracle Virtual Private Database policy prevents UPDATE/DELETE on audit_log table.',
 '21 CFR 11.10(e)', true),
('oracle', 'Signature Append-Only (VPD)',        'database_layer',
 'Oracle VPD prevents UPDATE/DELETE on electronic_signatures table.',
 '21 CFR 11.70', true),
('mysql', 'Audit Log Append-Only (User Perms)',  'database_layer',
 'MySQL user openval_app has INSERT/SELECT only on audit_log. No UPDATE or DELETE granted.',
 '21 CFR 11.10(e)', true),
('mysql', 'Signature Append-Only (User Perms)',  'database_layer',
 'MySQL user openval_app has INSERT/SELECT only on electronic_signatures.',
 '21 CFR 11.70', true),
('postgresql', 'Audit Chain Integrity',          'application_layer',
 'SHA-256 hash chain verified nightly by Celery task. Tamper detection across all databases.',
 '21 CFR 11.10(e)', true),
('oracle',     'Audit Chain Integrity',          'application_layer',
 'SHA-256 hash chain verified nightly by Celery task.',
 '21 CFR 11.10(e)', true),
('mysql',      'Audit Chain Integrity',          'application_layer',
 'SHA-256 hash chain verified nightly by Celery task. Binlog provides additional tamper evidence.',
 '21 CFR 11.10(e)', true),
('postgresql', 'ORM Parameterized Queries',      'application_layer',
 'All queries through SQLAlchemy ORM. No raw SQL concatenation. Prevents SQL injection.',
 '21 CFR 11.10(a)', true),
('oracle',     'ORM Parameterized Queries',      'application_layer',
 'All queries through SQLAlchemy ORM. No raw SQL concatenation.',
 '21 CFR 11.10(a)', true),
('mysql',      'ORM Parameterized Queries',      'application_layer',
 'All queries through SQLAlchemy ORM. No raw SQL concatenation.',
 '21 CFR 11.10(a)', true);

-- ============================================================
-- SECTION 12: INDEXES FOR ALL NEW TABLES
-- ============================================================

CREATE INDEX idx_access_reviews_site ON user_access_reviews (site_id);
CREATE INDEX idx_access_reviews_system ON user_access_reviews (system_id);
CREATE INDEX idx_access_reviews_status ON user_access_reviews (status);
CREATE INDEX idx_access_review_items_review ON user_access_review_items (review_id);
CREATE INDEX idx_access_review_items_user ON user_access_review_items (reviewed_user_id);

CREATE INDEX idx_revalidation_system ON revalidation_events (system_id);
CREATE INDEX idx_revalidation_status ON revalidation_events (status);
CREATE INDEX idx_revalidation_trigger ON revalidation_events (trigger_date DESC);

CREATE INDEX idx_dr_tests_site ON dr_bcp_tests (site_id);
CREATE INDEX idx_dr_tests_system ON dr_bcp_tests (system_id);
CREATE INDEX idx_dr_tests_date ON dr_bcp_tests (test_date DESC);
CREATE INDEX idx_dr_tests_result ON dr_bcp_tests (result);

CREATE INDEX idx_method_val_site ON method_validations (site_id);
CREATE INDEX idx_method_val_status ON method_validations (status);
CREATE INDEX idx_method_val_protocol ON method_validations (protocol_id);
CREATE INDEX idx_method_val_results ON method_validation_results (method_id);

CREATE INDEX idx_ext_access_log_system ON external_system_access_log (system_id);
CREATE INDEX idx_ext_access_log_user ON external_system_access_log (user_id);
CREATE INDEX idx_ext_access_log_occurred ON external_system_access_log (occurred_at DESC);

CREATE INDEX idx_data_migrations_site ON data_migrations (site_id);
CREATE INDEX idx_data_migrations_target ON data_migrations (target_system_id);
CREATE INDEX idx_data_migrations_status ON data_migrations (status);
CREATE INDEX idx_migration_exceptions ON data_migration_exceptions (migration_id);

CREATE INDEX idx_asl_vendor ON approved_supplier_list (vendor_id);
CREATE INDEX idx_asl_site ON approved_supplier_list (site_id);
CREATE INDEX idx_asl_status ON approved_supplier_list (approval_status);
CREATE INDEX idx_supplier_perf_vendor ON supplier_performance_records (vendor_id);

CREATE INDEX idx_cpp_cqa_parameter ON cpp_cqa_linkages (cpp_parameter_id);
CREATE INDEX idx_cpp_cqa_system ON cpp_cqa_linkages (system_id);
CREATE INDEX idx_capability_studies_site ON process_capability_studies (site_id);
CREATE INDEX idx_capability_studies_param ON process_capability_studies (parameter_id);

CREATE INDEX idx_db_compliance_dialect ON database_compliance_controls (db_dialect);

-- ============================================================
-- FINAL COMPLETE TABLE COUNT
-- ============================================================

SELECT
    COUNT(*) AS total_tables,
    'Tables across all 6 schema parts' AS note
FROM information_schema.tables
WHERE table_schema = 'public' AND table_type = 'BASE TABLE';
